#!/bin/bash

INPUT_FOLDER="$1"
OUTPUT_FOLDER="$2"
BUCKET="$3"
REMOTE_FOLDER="$4"

read -sp 'Enter encryption key: ' ENCRYPTION_KEY
echo ""

cd "$INPUT_FOLDER"

for dir in */; do
    NAME="${dir// /_}"
    FILENAME="${NAME%/}.tar.xz.asc"
    tar -cvJf - "$dir" | gpg -c --batch --passphrase "$ENCRYPTION_KEY" > "$OUTPUT_FOLDER/$FILENAME"
    b2 upload-file $BUCKET "$OUTPUT_FOLDER/$FILENAME" "$REMOTE_FOLDER/$FILENAME" &
done

wait
