#!/bin/bash

# Set folder with backups
if [[ -d '/media/paul/Linux Backups' ]]; then
    export BACKUP_DIR='/media/paul/Linux Backups'
elif [[ -d /run/timeshift/backup ]]; then
    export BACKUP_DIR='/run/timeshift/backup'
else
    echo 'Backup folder not found' && exit 1
fi

export LOGDIR="$BACKUP_DIR/logs"
export LOGFILE="$LOGDIR/$(date +%d-%m-%y_%H-%M-%S).log"
export RSYNC_PASSWORD=$(cat $HOME/.rsync.pwd)

if [[ $1 === 'timeshift' ]]; then
    export REMOTE_DIR='system/linux'
else
    export REMOTE_DIR='files/linux'
fi

# Check if NAS exists on LAN
ping -c 4 10.0.10.2 || (echo "Cannot connect to NAS" >> "$LOGFILE" && exit 1)

# Wait to sync if timeshift is running and creating a snapshot
while pgrep timeshift; do
	echo "Waiting for snapshot creation to finish..." >> "$LOGFILE"
	sleep 1m
done

function sync(){
    echo "Syncing $1 snapshots..." >> "$LOGFILE"
    rsync -az --no-perms --info=progress2 --delete "$BACKUP_DIR/$1" rsync@10.0.10.2::backups/$REMOTE_DIR >> "$LOGFILE"
    printf "%s\n\n" 'Done' >> "$LOGFILE"
}

sync $1
