#!/bin/bash

# Set folder with backups
if [[ -d '/media/paul/Linux Backups' ]]; then
    export BACKUP_DIR='/media/paul/Linux Backups'
elif [[ -d /run/timeshift/backup ]]; then
    export BACKUP_DIR='/run/timeshift/backup'
else
    echo 'Backup folder not found' && exit 1
fi

export LOGDIR="$BACKUP_DIR/logs"
export LOGFILE="$LOGDIR/$(date +%d-%m-%y_%H-%M-%S).log"

if [[ "$1" == 'timeshift' ]]; then
    export REMOTE_DIR='system/linux'
else
    export REMOTE_DIR='files/linux'
fi

# Check if NAS exists on LAN
ping -c 4 10.0.10.2 || (echo "Cannot connect to NAS" | tee -a "$LOGFILE" && exit 1)

# Wait to sync if timeshift is running and creating a snapshot
while pgrep timeshift; do
	echo "Waiting for snapshot creation to finish..." | tee -a "$LOGFILE"
	sleep 1m
done

function sync(){
    echo "Syncing $1 snapshots..." >> "$LOGFILE"
    rsync -a --no-perms --info=progress2 --delete --password-file=/home/paul/.rsync.pwd "$BACKUP_DIR/$1" rsync@10.0.10.2::backups/$REMOTE_DIR |& tee -a "$LOGFILE"
    printf "%s\n\n" 'Done' | tee -a "$LOGFILE"
}

sync $1
